# Generated by Django 2.1.5 on 2021-09-17 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_news_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='title',
            field=models.TextField(blank=True, null=True),
        ),
    ]
